In [1]:
import pandas as pd

In [33]:
df = pd.read_csv("two_cluster.csv")
illumina = pd.read_csv("Illumina_450k.txt", delimiter='\t')
data_tumor = "BRCA_Primary_Tumor.chr19.tsv"
tumor = pd.read_csv(data_tumor, delimiter="\t")
tumor = tumor.reset_index().rename(columns={"index":"location"})
tumor = tumor.rename(columns={"Unnamed: 0":"cg"})

In [34]:
tumor

,location,cg,6005486021_R01C01,6005486021_R02C01,6005486021_R03C01,6005486021_R04C01,6005486021_R05C01,6005486021_R06C01,6005486021_R01C02,6005486021_R02C02,...,6285633072_R02C02,6285633072_R04C02,6285633072_R03C02,6285633072_R05C02,7786923102_R06C02,7796806109_R01C01,7796806109_R05C01,7796806109_R06C01,7796806109_R04C01,7796806109_R02C01
0,0,cg15886596,10,10,7,7,7,7,8,6,...,13,14,11,12,13,13,12,11,12,12
1,1,cg12261117,61,44,40,30,39,30,37,38,...,45,50,41,41,74,71,72,52,63,48
2,2,cg18110419,442,617,652,689,658,636,607,514,...,665,565,608,596,701,488,625,639,701,508
3,3,cg25433760,521,976,960,979,950,971,977,969,...,965,964,953,958,962,973,976,978,973,974
4,4,cg23278040,162,486,760,224,818,561,549,715,...,462,207,54,270,366,384,788,434,592,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24666,24666,cg23652859,66,702,683,724,654,677,580,648,...,396,848,370,444,491,424,324,594,446,288
24667,24667,cg03567148,962,990,974,969,991,978,981,979,...,946,934,926,950,973,911,928,957,955,952
24668,24668,cg13678479,959,964,972,972,970,966,959,969,...,967,954,920,968,948,941,939,955,943,950
24669,24669,cg05617300,990,988,990,987,988,988,989,988,...,982,986,985,984,980,985,984,987,983,980
24670,24670,cg04407275,982,987,986,987,966,980,973,976,...,984,986,985,990,978,977,982,990,989,984

In [12]:
illumina

            IlmnID chrCHR    MAPINFO UCSC_RefGene_Name UCSC_RefGene_Group
0       cg00000029  chr16   53468112              RBL2            TSS1500
1       cg00000108   chr3   37459206   C3orf35;C3orf35         Body;3'UTR
2       cg00000109   chr3  171916037     FNDC3B;FNDC3B          Body;Body
3       cg00000165   chr1   91194674               NaN                NaN
4       cg00000236   chr8   42263294       VDAC3;VDAC3        3'UTR;3'UTR
...            ...    ...        ...               ...                ...
482416  cg27665860  chr11   68970673               NaN                NaN
482417  cg27665925  chr19   12098906               NaN                NaN
482418  cg27665985  chr15   66116727               NaN                NaN
482419  cg27666046  chr17   80279077            SECTM1              3'UTR
482420  cg27666123   chr5  126988029       CTXN3;CTXN3      5'UTR;TSS1500

[482421 rows x 5 columns]

In [31]:
df

,Unnamed: 0,location,split_value,normal_means,tumor_means,accuracy,squre_diff_value,label
0,22344,22344,788.5,876.288660,474.607490,0.938776,12224.995451,0
1,12142,12142,724.5,860.371134,589.066574,0.918367,1447.147036,0
2,12169,12169,348.5,547.969072,244.418863,0.918367,6222.552825,0
3,12244,12244,751.5,853.237113,552.791956,0.918367,285.871192,0
4,12268,12268,824.5,900.525773,503.011096,0.959184,5259.208738,0
...,...,...,...,...,...,...,...,...
329,13494,13494,315.5,190.000000,534.696255,0.938776,7996.479598,1
330,13495,13495,332.5,213.618557,551.087379,0.979592,9248.200429,1
331,14176,14176,267.5,141.876289,433.398058,0.979592,1550.080761,1
332,14179,14179,319.5,137.422680,522.135922,0.938776,3244.504544,1
333,24666,24666,352.5,228.536082,544.715673,0.979592,571.695591,1

In [38]:
merged = df.merge(tumor[["cg", "location"]], right_on="location", left_on="location").merge(illumina, left_on="cg", right_on="IlmnID")
merged

,Unnamed: 0,location,split_value,normal_means,tumor_means,accuracy,squre_diff_value,label,cg,IlmnID,chrCHR,MAPINFO,UCSC_RefGene_Name,UCSC_RefGene_Group
0,22344,22344,788.5,876.288660,474.607490,0.938776,12224.995451,0,cg24755177,cg24755177,chr19,54850645,LILRA4,TSS1500
1,12142,12142,724.5,860.371134,589.066574,0.918367,1447.147036,0,cg25690537,cg25690537,chr19,30022536,VSTM2B,Body
2,12169,12169,348.5,547.969072,244.418863,0.918367,6222.552825,0,cg14945937,cg14945937,chr19,30162771,PLEKHF1,5'UTR
3,12244,12244,751.5,853.237113,552.791956,0.918367,285.871192,0,cg05901613,cg05901613,chr19,30709527,NaN,NaN
4,12268,12268,824.5,900.525773,503.011096,0.959184,5259.208738,0,cg18722124,cg18722124,chr19,30862050,ZNF536,TSS1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,13494,13494,315.5,190.000000,534.696255,0.938776,7996.479598,1,cg09510559,cg09510559,chr19,36335144,NPHS1,Body
330,13495,13495,332.5,213.618557,551.087379,0.979592,9248.200429,1,cg25537669,cg25537669,chr19,36335320,NPHS1,Body
331,14176,14176,267.5,141.876289,433.398058,0.979592,1550.080761,1,cg27389185,cg27389185,chr19,38042123,ZNF540,TSS200
332,14179,14179,319.5,137.422680,522.135922,0.938776,3244.504544,1,cg03975694,cg03975694,chr19,38042472,ZNF540;ZNF540,5'UTR;1stExon
333,24666,24666,352.5,228.536082,544.715673,0.979592,571.695591,1,cg23652859,cg23652859,chr19,59092692,MGC2752,Body

In [41]:
merged[["label", "UCSC_RefGene_Name"]].to_csv("two_groups_of_genes.csv")